export const CONFIG = {
  MAPILLARY_TOKEN: "MLY|YOUR_CLIENT_TOKEN_HERE",
  SUPABASE_URL: "https://YOUR_PROJECT.supabase.co",
  SUPABASE_ANON_KEY: "YOUR_ANON_KEY_HERE",
  ROUND_TIME_SECONDS: 60,
  ROUNDS_PER_GAME: 5,
  MAX_PLAYERS: 4,
  SEARCH_RADIUS_METERS: 4000
};
